### ISSUE TITLE
This Portmanat APIs Depricated

### ISSUE THREAD

**Issue by Akhundoff** [dercoder/omnipay-portmanat#1]
APIs in portmant have been changed. That's why the package doesn't work. Also the portmanat code is no longer available. There is a bank card payment instead. I can help you update it if you want.

**Comment by dercoder** [comment]
That would be nice. Please create a PR and I will create a new Release

**Comment by Akhundoff** [comment]
I can tell you about new portmant APIs. My suggestion isn`t about writing the code side.
Portmanat will launch a new API in 1 week. This is the second amendment in the last 6 years. I can give you my portmanat account and explain it to you their documentaion(as you know, everything there is in Azerbaijani.).

**Comment by dercoder** [comment]
I don't think I have time to implement it now
